development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:ee4744959d833e6aad9bf271127476da@spinyfin.redistogo.com:9733/
  channel_prefix: Dog-Meetups_production
