development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("https://git.heroku.com/fierce-savannah-78648.git") { "redis://localhost:6379/1" } %>
  channel_prefix: Dog-Meetups_production
